# Use a Node.js base image
FROM node:14-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight nginx image to serve the built app
FROM nginx:alpine

# Copy the built app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

ENV REACT_APP_ENVIRONMENT=production
ENV REACT_APP_FRONTEND_URL=localhost
ENV REACT_APP_BACKEND_URL=localhost

COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the outside world
EXPOSE 80

# Test Nginx command
RUN nginx -t

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
